# Generated by Django 4.1.4 on 2023-01-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='count_comment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='count_like',
            field=models.IntegerField(null=True),
        ),
    ]
