# Generated by Django 4.1.7 on 2023-03-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_200',
            field=models.URLField(null=True),
        ),
    ]
