# Generated by Django 4.0.1 on 2022-12-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usualUserOrAdmin',
            new_name='usualUserOrModer',
        ),
    ]
