# Generated by Django 4.1.7 on 2023-03-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("votephoto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="photo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="votephoto.photo",
            ),
        ),
    ]
