# Generated by Django 4.1.7 on 2023-02-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0002_photo_date_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date_now',
        ),
    ]
