# Generated by Django 4.1.4 on 2023-01-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0002_photo_count_comment_photo_count_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='count_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='count_like',
            field=models.IntegerField(default=0),
        ),
    ]
