# Generated by Django 4.0.1 on 2022-12-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0002_alter_photo_photo_145x165_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_1680x1680',
        ),
    ]
