# Generated by Django 4.0.1 on 2022-12-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0002_rename_usualuseroradmin_user_usualuserormoder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usualUserOrModer',
            field=models.BooleanField(default=False, verbose_name='Модератор?'),
        ),
    ]
