# Generated by Django 4.1.4 on 2023-01-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0004_alter_photo_options_alter_photo_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_delete',
            field=models.ImageField(blank=True, null=True, upload_to='delete_photos/%Y/%m/%d'),
        ),
    ]
