# Generated by Django 4.1.4 on 2023-01-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0005_photo_photo_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='moderator',
        ),
    ]
