# Generated by Django 4.1.4 on 2023-01-15 09:14

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0006_remove_user_moderator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AddField(
            model_name='photo',
            name='state',
            field=django_fsm.FSMField(default='Not verified', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votephoto.photo', verbose_name='Фотография, которая содержит лайк'),
        ),
    ]
