# Generated by Django 4.1.7 on 2023-03-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("votephoto", "0006_alter_notification_message"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="like",
            table="like_votephoto",
        ),
    ]
