# Generated by Django 4.1.4 on 2023-01-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0007_alter_like_options_photo_state_alter_like_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
    ]
