# Generated by Django 4.1.4 on 2023-01-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0010_alter_comment_table_alter_like_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_votephoto',
        ),
    ]
