# Generated by Django 4.1.4 on 2023-01-23 12:52

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0011_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='state',
            field=django_fsm.FSMField(default='Not verified', max_length=50, protected=True, verbose_name='Статус фотографии'),
        ),
    ]
