# Generated by Django 4.1.4 on 2023-01-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votephoto', '0012_alter_photo_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='delete_photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='date_delete',
            field=models.DateTimeField(null=True),
        ),
    ]
