from vote_photo.views.admin.admin import *
from vote_photo.views.auth.auth import *
from vote_photo.views.celery.celery_view import *
from vote_photo.views.comment.comment import *
from vote_photo.views.like.like import *
from vote_photo.views.notification.notification import *
from vote_photo.views.photo.photo import *
from vote_photo.views.photo.photo_one import *
from vote_photo.views.photo.photo_user import *
from vote_photo.views.update.update_data import *
from vote_photo.views.update.update_token_by_vk import *
