# Generated by Django 4.1.7 on 2023-03-27 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vote_photo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="dateCreate",
            new_name="date_create",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="dateUpdate",
            new_name="date_update",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="Parent",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="dateCreate",
            new_name="date_create",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="dateUpdate",
            new_name="date_update",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="info_published",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="modification",
        ),
        migrations.AlterModelTable(
            name="comment",
            table="comments",
        ),
        migrations.AlterModelTable(
            name="like",
            table="likes",
        ),
        migrations.AlterModelTable(
            name="notification",
            table="notifications",
        ),
        migrations.AlterModelTable(
            name="photo",
            table="photos",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
