# Generated by Django 4.1.7 on 2023-04-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vote_photo", "0004_alter_photo_new_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="date_create",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
