# Generated by Django 4.1.7 on 2023-04-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vote_photo", "0005_notification_date_create"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="date_send_notification",
            field=models.DateTimeField(null=True),
        ),
    ]
