# Generated by Django 4.1.7 on 2023-04-11 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vote_photo", "0006_notification_date_send_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="date_send_notification",
        ),
    ]
